service: Serverless

frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-2
  memorySize: 512
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    # Add the following lines:
    events:
      - http:
          path: hello
          method: post

custom:
  pythonRequirements:
    dockerizePip: false

plugins:
  - serverless-python-requirements
